name: Build and Push Docker Image

on:
  workflow_dispatch:
  schedule: '0 18 * * *'

env:
  PROJECT_ID: high-theme-384006
  IMAGE_NAME: hello-app
  REGISTRY_LOCATION: us-central-1
  REPOSITORY: hello-chart

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up Google Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v0.4.3
      #   with:
      #     project_id: ${{ env.PROJECT_ID }}
      #     service_account_key: ${{ secrets.GCP_SA_KEY }}
      #     export_default_credentials: true

      - id: 'auth'
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: 'docker/login-action@v1'
        name: 'Docker login'
        with:
          registry: '${{ env.REGISTRY_LOCATION }}-docker.pkg.dev'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: Build and tag Docker image
        run: |
          docker build -t "${{ env.REGISTRY_LOCATION }}-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push "${{ env.REGISTRY_LOCATION }}-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/${{ env.IMAGE_NAME }}:${{ github.sha }}"

      - name: Set Docker image URL as an output
        id: docker-image-url
        run: |
          echo ::set-output name=docker_image_url::${{ env.REGISTRY_LOCATION }}-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/${{ env.IMAGE_NAME }}:${{ github.sha }}

